services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend/bloguer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/bloguer:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: